pretend: false
all: false
force: false
lastgenre: true
xtractor: true
from_title: true
parent_genres: true
genre_rosamerica_strong: 0.8
genre_electronic_strong: 0.8
genre_electronic_prepend: 0.5
genre_electronic_append: 0.45
